version: "3"

services:
  redis:
    image: redis:5-alpine
    restart: always
    networks:
      - network

  web-api:
    restart: always
    build: api
    ports:
      - "8001:8000"
    volumes:
      - ./api:/usr/src/app
    env_file:
      - api/.env
    depends_on:
      - redis
    command: [ "python3", "manage.py", "runserver", "0.0.0.0:8000" ]
    #    command: [ "poetry", "run", "python3", "manage.py", "runserver", "0.0.0.0:8000" ]
    networks:
      - network

  worker:
    restart: always
    build: api
    env_file:
      - api/.env
    volumes:
      - ./api:/usr/src/app
    command: [ 'celery', '-A', 'config', 'worker', '-l', 'INFO' ]
    depends_on:
      - redis
    networks:
      - network

  celery-beats:
    restart: always
    build: api
    env_file:
      - api/.env
    volumes:
      - ./api:/usr/src/app
    command: [ 'celery', '-A', 'config', 'beat', '-l', 'INFO' ]
    depends_on:
      - redis
    networks:
      - network

  bot:
    restart: always
    build: bot
    env_file:
      - bot/.env
    volumes:
      - ./bot:/usr/src/app
    command: [ 'python3', 'main.py' ]
    networks:
      - network

networks:
  network:
    driver: bridge
