version: "3"

services:
  redis:
    image: redis:5-alpine
    restart: always

  web-api:
    restart: always
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    command: [ "poetry", "run", "python3", "manage.py", "runserver", "0.0.0.0:8000" ]