version: "3"

services:
  redis:
    image: redis:5-alpine
    restart: always

  web-api:
    restart: always
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/usr/src/app
      - ./db:/usr/src/db
    env_file:
      - .env
    depends_on:
      - redis
    command: [ "python3", "manage.py", "runserver", "0.0.0.0:8000" ]
  #    command: [ "poetry", "run", "python3", "manage.py", "runserver", "0.0.0.0:8000" ]

  worker:
    restart: always
    build: .
    env_file:
      - .env
    volumes:
      - .:/usr/src/app
    command: [ 'celery', '-A', 'config', 'worker' ]
    depends_on:
      - web-api
      - redis

  celery-beats:
    restart: always
    build: .
    env_file:
      - .env
    volumes:
      - ./db:/usr/src/db
    command: [ 'celery', '-A', 'config', 'beat', '-l', 'INFO', '--scheduler', 'django_celery_beat.schedulers:DatabaseScheduler' ]
    depends_on:
      - web-api
      - redis
